name: 3D Contribution Graph Updater

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  generate-3d:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          renderer: "both"  # Generate both standard and animated versions
          theme: "auto"     # Automatic light/dark theme detection
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n x-access-token:${{ secrets.GH_PAT }} | base64)"

      - name: Commit & Push Changes
        run: |
          git add ./profile-3d-contrib/*
          git commit -m "🔄 Automated 3D Contribution Graph Update" || echo "No changes to commit"
          git pull --rebase origin main  # Prevent divergent histories
          git push origin main
