name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      # Update the action version here
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: path/to/your/artifact
