name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake Contribution Graph
        uses: Platane/snk@master
        with:
          github_user_name: "MdIbuA"
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Upload Snake Contribution Graph
        uses: actions/upload-artifact@v2
        with:
          name: contribution-snake
          path: dist/github-contribution-grid-snake.svg
